# fly.toml app configuration file generated for gerenciadorplanilhafinanceira on 2025-05-21T12:00:10-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gerenciadorplanilhafinanceira'
primary_region = 'gru'

[processes]
worker = "dotnet GerenciadorPlanilhaFinanceira.dll"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
